# Generated by Django 5.1.15 on 2026-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_hash', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('servicing', 'Servicing'), ('marketing', 'Marketing'), ('analytics', 'Analytics'), ('cross_sell', 'Cross-sell'), ('account_aggregator', 'Account Aggregator')], max_length=30)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('pending', 'Pending')], max_length=10)),
                ('channel', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KycRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_hash', models.CharField(max_length=64, unique=True)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('risk_reason', models.CharField(blank=True, max_length=200)),
                ('last_kyc', models.DateField()),
                ('pep', models.BooleanField(default=False)),
                ('pep_note', models.CharField(blank=True, max_length=200)),
                ('sanctions', models.CharField(choices=[('clear', 'Clear'), ('potential_match', 'Potential match')], default='clear', max_length=20)),
                ('sanctions_checked', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
