# Generated by Django 5.1.15 on 2026-10-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('sources', '0002_seed_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trust_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('score_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FieldWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'name'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('dob', 'dob')], max_length=20, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_reason', models.CharField(max_length=200)),
                ('linked_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mdm.customer')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_link', to='ingestion.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='GoldenField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'name'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('dob', 'dob')], max_length=20)),
                ('value', models.TextField()),
                ('trust', models.DecimalField(decimal_places=2, max_digits=3)),
                ('conflicts', models.PositiveSmallIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_fields', to='mdm.customer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.sourcerecord')),
            ],
            options={
                'ordering': ['customer', 'field'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'field'), name='one_golden_value_per_field')],
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('record_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ingestion.sourcerecord')),
                ('record_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ingestion.sourcerecord')),
            ],
            options={
                'ordering': ['status', '-points'],
                'constraints': [models.UniqueConstraint(fields=('record_a', 'record_b'), name='one_suggestion_per_pair')],
            },
        ),
    ]
