# Generated by Django 5.1.15 on 2026-10-09 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('mdm', '0002_seed_field_weights'),
        ('sources', '0002_seed_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenfield',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.source'),
        ),
        migrations.AlterField(
            model_name='goldenfield',
            name='source_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingestion.sourcerecord'),
        ),
        migrations.CreateModel(
            name='FieldCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'name'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('dob', 'dob')], max_length=20)),
                ('value', models.TextField()),
                ('previous_value', models.TextField(blank=True)),
                ('evidence_ref', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('proposed_by_name', models.CharField(max_length=150)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by_name', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='mdm.customer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='goldenfield',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.fieldcorrection'),
        ),
    ]
