# Generated by Django 5.1.15 on 2026-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_alter_goldenfield_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcorrection',
            name='field',
            field=models.CharField(choices=[('name', 'name'), ('father_name', 'father_name'), ('dob', 'dob'), ('gender', 'gender'), ('pan', 'pan'), ('aadhaar', 'aadhaar'), ('ckyc', 'ckyc'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('perm_address', 'perm_address'), ('occupation', 'occupation'), ('income', 'income')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldweight',
            name='field',
            field=models.CharField(choices=[('name', 'name'), ('father_name', 'father_name'), ('dob', 'dob'), ('gender', 'gender'), ('pan', 'pan'), ('aadhaar', 'aadhaar'), ('ckyc', 'ckyc'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('perm_address', 'perm_address'), ('occupation', 'occupation'), ('income', 'income')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='goldenfield',
            name='field',
            field=models.CharField(choices=[('name', 'name'), ('father_name', 'father_name'), ('dob', 'dob'), ('gender', 'gender'), ('pan', 'pan'), ('aadhaar', 'aadhaar'), ('ckyc', 'ckyc'), ('mobile', 'mobile'), ('email', 'email'), ('address', 'address'), ('perm_address', 'perm_address'), ('occupation', 'occupation'), ('income', 'income')], max_length=20),
        ),
    ]
