# Generated by Django 5.1.15 on 2026-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0005_prototype_field_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pan_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
