# Generated by Django 5.1.15 on 2026-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='ckyc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='ckyc_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='income',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='pan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='pan_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='perm_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
