"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Values come from the .env file at the repo root (copy .env.example to .env).
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Render sets this to the service's own hostname (e.g. lumina-cri-api.onrender.com).
if os.getenv('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'sources',
    'ingestion',
    'mdm',
    'api',
    'accounts',
    'audit',
    'stewardship',
    'compliance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the admin's CSS and JS when there is no separate web server (hosted demo).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # Lumina's own database.
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'lumina'),
        'USER': os.getenv('POSTGRES_USER', 'lumina'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5433'),
    }
}



def _database_from_url(url):
    """Turn postgresql://user:password@host:port/name?sslmode=require into Django settings."""
    parts = urlparse(url)
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parts.path.lstrip('/'),
        'USER': unquote(parts.username or ''),
        'PASSWORD': unquote(parts.password or ''),
        'HOST': parts.hostname,
        'PORT': str(parts.port or 5432),
        'OPTIONS': dict(parse_qsl(parts.query)),
    }


# Hosted demo (Render + Neon): one connection string instead of the POSTGRES_* values.
DATABASE_URL = os.getenv('DATABASE_URL', '')
if DATABASE_URL:
    DATABASES['default'] = _database_from_url(DATABASE_URL)

# Fake FLEXCUBE core banking system. Connectors read it with raw SQL; Django never migrates it.
# When only DATABASE_URL is set, FLEXCUBE is the src_flexcube database on the same server.
FLEXCUBE_DB_URL = os.getenv('FLEXCUBE_DB_URL', '')
if not FLEXCUBE_DB_URL and DATABASE_URL:
    FLEXCUBE_DB_URL = urlparse(DATABASE_URL)._replace(path='/src_flexcube').geturl()

# Key for encrypting PAN and CKYC numbers (Fernet key). Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Required when DJANGO_DEBUG is false; in development a key is derived from DJANGO_SECRET_KEY if missing.
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')

# Fake Salesforce API response and branch CSV uploads, kept in the repo under fake_sources/.
SALESFORCE_MOCK_FILE = os.getenv('SALESFORCE_MOCK_FILE') or str(BASE_DIR.parent / 'fake_sources' / 'salesforce' / 'contacts.json')
BRANCH_CSV_DIR = os.getenv('BRANCH_CSV_DIR') or str(BASE_DIR.parent / 'fake_sources' / 'branch_csv')

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
# The React dev server proxies /api to Django, so the browser sends its own origin with each request.
# Spaces and a trailing slash are ignored, so "https://lumina-cri.vercel.app/ " still works.
CSRF_TRUSTED_ORIGINS = [
    o.strip().rstrip('/') for o in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173').split(',') if o.strip()
]

REST_FRAMEWORK = {
    # Every endpoint needs a logged-in user unless it says otherwise. This is customer data.
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
    # Signed in AND given a Lumina role (see accounts/roles.py). Views add finer checks on top.
    'DEFAULT_PERMISSION_CLASSES': ['api.permissions.HasRole'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    # Hosted over HTTPS behind Render's proxy: trust its scheme header and send cookies over HTTPS only.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
