# Generated by Django 5.1.15 on 2026-10-08 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('view_customer', 'Viewed customer'), ('export', 'Exported customers'), ('sync_source', 'Synced source'), ('update_source', 'Changed source'), ('merge', 'Merged records'), ('keep_apart', 'Kept records apart'), ('denied', 'Access denied')], db_index=True, max_length=20)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
