# Generated by Django 5.1.15 on 2026-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('view_customer', 'Viewed customer'), ('export', 'Exported customers'), ('sync_source', 'Synced source'), ('update_source', 'Changed source'), ('merge', 'Merged records'), ('keep_apart', 'Kept records apart'), ('denied', 'Access denied'), ('corr_proposed', 'Proposed correction'), ('corr_approved', 'Approved correction'), ('corr_rejected', 'Rejected correction')], db_index=True, max_length=20),
        ),
    ]
